name: "CI Basics"

on:
  push: ~
  workflow_dispatch: ~

jobs:
  hello:
    name: "Hello world"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Say hello"
        run: echo "Hello world"

  hello2:
    name: "Hello world 2"
    runs-on: "ubuntu-latest"
    continue-on-error: true
    steps:
      - name: "Say Hello again"
        run: |
          echo "Hello world"
          echo "Hello world"
          exit 1
      - name: "Say Coucou"
        run: echo "Coucou"

  hello3:
    name: "Hello world 3"
    runs-on: "ubuntu-latest"
    steps:
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

  hello4:
    needs: ["hello", "hello2", "hello3"]
    name: "Hello world 3"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Say hello 3"
        run: echo "Hello world 3"